import Head from 'next/head'

import Hero from '../components/Hero';
import Feautures from '../components/Feautures';
import Services from '../components/Services';
import About from '../components/About';
import Footer from '../components/Footer';

export default function Home() {


  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Feautures />
      <Services />
      <About />
      <Footer />
    </div>
  )
}
